### ISSUE TITLE
Question: Why don't all content analysis bullets show

### ISSUE THREAD

**Issue by smustgrave** [Yoast/javascript#1062]
This is more of a question but how come all of the bullets under content analysis don't always show?
Sometimes when things turn green they disappear.

**Comment by Djennez** [comment]
We use GitHub exclusively for well-documented bug reports or feature requests. This is not a support forum for questions and case-specific support. To receive free support for Yoast SEO we have the following channels:
- [Yoast Knowledge base](http://kb.yoast.com/)
- [Support forums](https://wordpress.org/support/plugin/wordpress-seo) on WordPress.org

If you are a premium customer, you may also contact our team of support engineers directly via e-mail.

Your issue unfortunately does not contain enough information to be a viable bug report or feature request. If you feel like your bug or enhancement is a valid one and should be reviewed by us, then please use the provided templates, read our [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md) and submit a new issue.

Thank you for your understanding.
