### ISSUE TITLE
Refactor improved analysis functionality to use `ParsedPaper` instead of `tree` 

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#117]
Related #112 

## Summary
See #112 ; we need to have metadata to make certain assessments, which are currently not in the tree. Therefore, we need the to-be-created `parsedPaper` instance to be passed to the analyses that currently use the tree.

**Comment by manuelaugustin** [comment]
This issue is closed because changes in the tree parser architecture have most likely obsolete. Can be re-opened if necessary.
