### ISSUE TITLE
Refactor tree folder structure to accommodate metadata

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#119]
Related #112 

## Summary
We need to refactor the folder structure to accomodate the metadata functionality.

Spec:
Refactor folder structure:

- ~tree~ -> **parsedPaper**
  - **Assess**
unchanged
  - **Builder**
    - Metadata
_Will be filled out in a separate issue_
    - Tree
    What used to be in builder.
    - parsePaper.js
-> imports metadata and tree builders.
    - index.js
-> imports parsePaper and exports as default.
  - **Research**
  unchanged
  - **Structure**
  unchanged

**Comment by hansjovis** [comment]
Can we rename the **builder** module to **build**, since we are already changing it entirely?
This would make the naming more consistent (**assess**, **research** and **build**) 😄.

**Comment by hansjovis** [comment]
And perhaps change **structure** to **treeStructure**.
After changing the `tree` folder to `parsedPaper`, it would make it clear that this module is about the structure of the tree, rather than the structure of the paper.
