### ISSUE TITLE
SEO results are not matching with online tool https://yoast.com/research/real-time-content-analysis/

### ISSUE THREAD

**Issue by siddu-nc** [Yoast/javascript#1201]
## Explanation

The YoastSeo content assessment score and the [Real time content analysis](https://yoast.com/research/real-time-content-analysis/) tool score is not matching, even though both the content feeding is same.

The goal is real time content analysis tool score should match with the yoast seo plugin tool. 

## Technical decisions

After debugging the real time tool is using tinymce editor which is generating an HTML version of the input and the assessment score generating on HTML version which causes an uneven in the score.

Please try to parse the html and use only plain text of the input which will match the score with the plugin based.

Attaching the screenshot of the score with the same text input.

![image](https://user-images.githubusercontent.com/69191762/134636683-3c0b831c-f619-44e8-a868-946d381ef201.png)

![image](https://user-images.githubusercontent.com/69191762/134636756-6ba80fe1-9638-4919-86e9-7431e1d27695.png)

**Comment by Djennez** [comment]
The online content analysis is unfortunately a bit outdated and can not / should not be compared to the analysis in the plugin. Therefore I am closing this as a non-bug.

**Comment by siddu-nc** [comment]
@Djennez thanks for your clarification.

Please can you let me know the tool [Real content analysis](https://yoast.com/research/real-time-content-analysis/) what yoastseo version is it using.
