### ISSUE TITLE
Save morphologydata on the webworker

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#121]
Related #112 

## Summary
Create the metadata builder function(s), and combine them in `parsePaper.js` and the `index.js` (see #119 ) of the parsedPaper folder. Also, save morphology on the webworker.

In this first iteration, only one builder function should be made:
 * A function to generate keyphrase (morphological) forms for the main keyphrase and its synonyms. 

## Technical decisions
On initialization, save the morphologydata as a (private) property on the webworker, so that the parsedPaper builders can use it to build topic forms. We need to gracefully handle non-existence of `morphologyData` (when it has not been loaded yet) and non-existence of `morphologyData[ language ]` (when the language is not supported morphology-wise).

We can call `collectKeyphraseAndSynonymsForms` to build the keyphrase forms. It already handles non-existence of `morphologyData`, but we need to check just in case.

**Comment by manuelaugustin** [comment]
Issue not clear - needs new spec
