### ISSUE TITLE
(S)CSS imports from node_modules using ~ does not work everywhere.

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#126]
## Summary
Importing `.(s)css` from a different package using `~@yoast/....` only works in environments that are compiled using `webpack`. Therefore, we need a more reliable approach to do this. @diedexx suggestion is to move all the (s)css to `styled-components` that we can use where needed.

## Explanation
At the moment, it seems impossible to build certain packages because there are (s)css imports that use the `~`. We need to find a durable fix for this as soon as possible.

## Technical decisions
Importing using `~` only works in packages that are compiled using `webpack`, we also need a solution for other packages.

## Feedback?
If someone has an idea, please comment on this issue.

**Comment by diedexx** [comment]
Related to https://github.com/Yoast/javascript/issues/95

**Comment by bintzandt** [comment]
I guess this issue can be closed right? Since we divided this into several smaller issues.

**Comment by diedexx** [comment]
Replaced by 
- https://github.com/Yoast/javascript/issues/141
- https://github.com/Yoast/javascript/issues/143
- https://github.com/Yoast/javascript/issues/145
- https://github.com/Yoast/javascript/issues/151
- https://github.com/Yoast/javascript/issues/152
