### ISSUE TITLE
Remove error states from the FacebookImage and TwitterImage components

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#127]
Currently, the FacebookImage component contains two error states: one which is shown when the uploaded image is too small, and one general error message. Those are shown within the FacebookImage component itself:
<img width="560" alt="Schermafbeelding 2019-03-26 om 10 53 50" src="https://user-images.githubusercontent.com/17744553/54987770-7610d400-4fb5-11e9-9e4f-9f04cd85fb6b.png">

However, we've decided to move the error messages about images to a notification, see: https://github.com/Yoast/roadmap/issues/21#issuecomment-469585683 

This means the error states need to be removed from the FacebookImage component. Since the TwitterImage component originally was a copy from the FacebookImage component, TwitterImage should also be checked and the relevant error states should be removed.

**Comment by igorschoester** [comment]
- What should get displayed when the status is errored?
- What should get displayed when the size is too small?

The placeholder?

**Comment by IreneStr** [comment]
Yes 😄

**Comment by johannadevos** [comment]
Please note that there is no preview yet of the placeholder image when the status of the image is `loading`.

**Comment by johannadevos** [comment]
@IreneStr Should the checks for failing images also be removed from the `localhost` preview and the unit tests?

**Comment by IreneStr** [comment]
Please remove them from the unittests, but keep them in the preview. If you remove them from the preview now, we have to add them again very soon. It's no problem to have some work-in-progress previews in the example for now.

**Comment by IreneStr** [comment]
@johannadevos I've discussed this with @herregroen and it's better to wait with removing the error states until we have implemented the global state in the second phase of the reactification. Otherwise, we have to write a 'fake' state now to make sure the component can still render with an image. This means I will remove this issue from the process.
