### ISSUE TITLE
Fix sass in configuration wizard

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#141]
## Summary

The path to the sass file for the configuration wizard needs to be adjusted.

## Explanation

In the JavaScript monorepo the sass file for the configuration wizard has been removed and needs to be created in @yoast/configuration-wizard/src
In the plugin repo the path to this file needs to be adjusted so the file can be found.
Check if there are other locations where this file is used.

## Technical decisions

2 PRs are needed for this. One on the JavaScript monorepo and one on the plugin repo.

**Comment by bintzandt** [comment]
I don't know if what I am doing is on the right track. Therefore I'm adding the `help wanted` label so the one who is doing the code review can pay special attention to whether I'm doing the right thing.
