### ISSUE TITLE
Remove loadingSpinner.scss

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#152]
## Explanation

The loadingSpinner.scss file is not used, so it can be removed.
This file needs to be (safely) removed:
javascript/packages/yoast-components/css/loadingSpinner.scss

**Comment by bintzandt** [comment]
`loadingSpinner.scss` is currently used in `all.scss` (in `yoast-components/css`) which in turn is used in the plugin in `css/src/yoast-components.scss` and `css/src/alerts.scss`. 

The `loadingSpinner.scss` is directly imported in the `metabox.scss` file located in `css/src/metabox.scss`.

What should be done with all these instances? Simply removing the `loadingSpinner.scss` is probably breaking these instances. Is there any method to check whether the imported `sass` is actually used?
