### ISSUE TITLE
Truncate TwitterTitle and TwitterDescription based on width and number of lines

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#157]
I discussed the description and title length a bit in the #product channel, because the Twitter docs are inconsistent, and not reflecting the reality in some regards. 

The conclusion is that we should go for:

_Description_
- `summary`: 3 lines maximum. The width of each line is 476px.
- `summary-large-image`: 2 lines maximum. The width of each line is 476px.

_Title_
- both types: 1 line maximum. The width of each line is 476px.

For implementation directions, see https://github.com/Yoast/javascript/issues/49#issuecomment-477127056

Parent https://github.com/Yoast/javascript/issues/48

## To do
- [ ] Implement the truncation
- [ ] Write tests for the truncation function
- [ ] Update or create snapshot for the component

**Comment by igorschoester** [comment]
Don't forget the nice `...` truncation 😄

**Comment by bintzandt** [comment]
This has been fixed in #477 since it did not feel useful to add the truncation function without being able to see the final results.

**Comment by maartenleenders** [comment]
Will be fixed in https://github.com/Yoast/javascript/pull/477

**Comment by maartenleenders** [comment]
We ended up going for a CSS solution that limits the number of lines and truncates with an ellipsis (line-clamp). (see https://github.com/Yoast/javascript/pull/477)
