### ISSUE TITLE
Add a message to yarn test if the premium-configuration is not installed

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#16]
## Summary
The test suites fail if `yoastseo` does not have the `premium-configuration`. This can be fixed manually by running `grunt get-premium-configuration` in the `packages/yoastseo` directory. However, we want to give feedback to the user that this needs to happen.

## Explanation
Ensure that `yarn lint` gives an error if the `premium-configuration` is not installed. This allows the user to fix the test. The solution that fixes the problem is running `grunt get-premium-configuration` in the `packages/yoastseo` directory.

**Comment by nataliashitova** [comment]
With the changes implemented for this issue, it became impossible to use a local branch in `premium-configuration`, which makes the development of morphological support features difficult.

**Comment by bintzandt** [comment]
We have overseen this problem. I'm currently working on a better fix. Could you test if it works when I'm done? I'll slack you then.
