### ISSUE TITLE
Unchecked runtime.lastError in components example

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#162]
1. Navigate to `javascript/apps/components`
2. Run `yarn install` and `yarn start`
3. Go to `localhost:3333`
4. Open your console.
5. Click mulitple buttons at the top.
6. See the following error:
<img width="593" alt="Schermafbeelding 2019-03-27 om 16 21 40" src="https://user-images.githubusercontent.com/17744553/55088703-7a6be880-50ac-11e9-8a58-114f0ce6c51d.png">

**Comment by diedexx** [comment]
This is due to the JavaScript Errors Notifier (Chrome) extension. I'm not sure if this is our responsibility to fix. 
what do you think @IreneStr?

**Comment by IreneStr** [comment]
@diedexx I had never seen the error before the monorepo. That’s why I reported it. If you’re 100% sure it comes from an extension, feel free to close the issue. Maybe the creation of the monorepo coincided with an update of that extension.

**Comment by diedexx** [comment]
I expect there to be an underlying problem with the monorepo code that causes the JS Errors Notifier extension to be unable to handle errors properly. The `Unchecked runtime.lastError` exception only occurs after another error (doesn't seem to matter where this error is thrown) while this extension is active.
The only negative downside I can see thus far is that the extension is now no longer capable of showing those errors. 

I personally think it's not worth the time to investigate what exactly is causing this and if it can be prevented in the first place, as everything else (besides the extension) is operating normally.
