### ISSUE TITLE
node-sass gets installed when you run "npm install yoast-components"

### ISSUE THREAD

**Issue by Xyfi** [Yoast/javascript#166]
## Explanation

Installing `yoast-components` as a dependency takes very long due to node-sass having to be compiled on mac.

This is due to the following dependency:

```
"optionalDependencies": {
    "grunt-scss-to-json": "^1.0.1"
  },
```

Node-sass isn't necessary when installing yoast-components as a regular dependency.

**Comment by IreneStr** [comment]
The first thing to try is adding `"grunt-scss-to-json": "^1.0.1"` as a dev-dependency instead of an `optionalDependencies`. 

@Xyfi thinks the `optionalDependencies` might be Windows-related, so please test on Windows.
