### ISSUE TITLE
Refactor npm/yoast-components into @yoast/components

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#2]
## Summary

De npm/yoast-components package needs to be spit up into 4 packages.

## Explanation

These are the 4 new packages that need to be created:
- @yoast/compontents
- @yoast/search-metadata-previews
- @yoast/social-metadata-previews
- @yoast/configuration-wizard

## Technical decisions

This issue needs to be split up in smaller issues.

## Feedback?
@atimmer

**Comment by diedexx** [comment]
This issue has been split up.
