### ISSUE TITLE
Make internal linking changes feature-flag compatible

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#204]
## PRs
https://github.com/Yoast/javascript/pull/206
https://github.com/Yoast/wordpress-seo-premium/pull/2343

## Explanation

The new internal linking functionality was developed as an improvement of the currently available functionality, not as an option to choose for one or the other analysis. We need to change this to accommodate a feature flag.

**Comment by hansjovis** [comment]
Blocked until the feature toggle functionality has been merged (e.g. #https://github.com/Yoast/wordpress-seo/pull/12723).

**Comment by nataliashitova** [comment]
Both PRs associated with this issue have been merged. Closing the issue.
