### ISSUE TITLE
Check whether uploaded Twitter image meets requirements

### ISSUE THREAD

**Issue by johannadevos** [Yoast/javascript#212]
## Check requirements

When the user uploads an image for the Twitter preview, this image must meet the following requirements (see [here](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image) and [here](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary)):

* Images must be less than 5MB in size. 
* JPG, PNG, WEBP and GIF formats are supported. 
* Only the first frame of an animated GIF will be used. 
* SVG is not supported.
* Dimensions for `summary_large_image` card: minimum 300x157, maximum 4096x4096.
* Dimensions for `summary` card: minimum ~~144x144~~ 200x200, maximum 4096x4096.

## Show notification if requirement isn't met
If a file is uploaded to the media library that does not meet these requirements, a notification should appear in the preview (this was specified in the [roadmap](https://github.com/Yoast/roadmap/issues/21)):

<img width="584" alt="54279211-ca1ec000-4594-11e9-8e38-023225e3365c" src="https://user-images.githubusercontent.com/20280513/55783897-b9883980-5aaf-11e9-8427-12962de57ac4.png">

**Instead of the notification shown above, use the already existing Alert component (type: warning).**

The text of the notification should be adjusted to the particular requirement(s) that wasn't / weren't met, see [below](https://github.com/Yoast/javascript/issues/212#issuecomment-483148902). A notification should also be shown if an image meets the requirements, but fails to load for other reasons. 

If multiple requirements are not met, combine all warnings into one alert, starting with the following sentence "The uploaded image has the following issue(s):"

## Technical decisions

* If multiple requirements aren't met, we show multiple notifications, one for each unmet requirement.
* Currently, `TwitterImage.js` contains its own checks for failing images, but these will be removed in #127.

## To do
- [ ] Implement the requirement checks.
- [ ] Show a warning if a requirement is not met.
- [ ] Write tests for the requirement checks.
- [ ] Update/create a snapshot for the component. Don't forget to test the case where multiple requirements are not met.

**Comment by johannadevos** [comment]
@IreneStr Is a similar issue required for Facebook? How/where will we deal with failing Facebook images?

**Comment by jono-alderson** [comment]
Let's up the minimum size to 200x200. Then it's consistent between FB/Twitter, and, we avoid any unpleasant scaling at lower sizes.

**Comment by johannadevos** [comment]
@jono-alderson Are you talking about the `summary` card only, or also `summary_large_image`? (Because for the latter, the minimum dimensions aren't square)

**Comment by jono-alderson** [comment]
Just for `summary` :)

**Comment by thijsdevalk** [comment]
Notification copy for when the requirements aren't met:

- The file size of the uploaded image is too large for Twitter. File size must be less than 5MB.
- The format of the uploaded image is not supported. The supported formats are: JPG, PNG, WEBP and GIF.
- You have uploaded a GIF. Please note that, if it’s an animated GIF, only the first frame will be used.
- The image you are trying to upload is too small. The minimum dimensions for this image are 300x157/200x200 pixels. The maximum dimensions are 4096x4096 pixels.
- The image you are trying to upload is too big. The maximum dimensions for this image are 4096x4096 pixels. The minimum dimensions are 300x157/200x200 pixels.
- Something went wrong with the uploaded image. Please try uploading the image again.

The second one can be used for both the second and the fourth requirement in your list. The last one is the general notification for when something went wrong, but we don't know what.
