### ISSUE TITLE
Check whether uploaded Facebook image meets requirements

### ISSUE THREAD

**Issue by johannadevos** [Yoast/javascript#214]
## Check requirements

When the user uploads an image for the Facebook preview, this image must meet the following requirements:

* The minimum dimensions for the image are 200x200 px.

## Show notification if requirement isn't met
If a file is uploaded to the media library that does not meet this requirement, a notification should appear in the preview (this was specified in the [roadmap](https://github.com/Yoast/roadmap/issues/21)):

<img width="584" alt="54279211-ca1ec000-4594-11e9-8e38-023225e3365c" src="https://user-images.githubusercontent.com/20280513/55783897-b9883980-5aaf-11e9-8427-12962de57ac4.png">

A notification should also be shown if an image meets the requirements, but fails to load for other reasons. 

Of course, the notification should say "Facebook" rather than Twitter", and the text of the notification should be adjusted to the particular reason for failure (see [here](https://github.com/Yoast/javascript/issues/214#issuecomment-483149837)).

**Instead of the notification shown above, use the already existing Alert component (type: warning).**

## Technical decisions

* Currently, `FacebookImage.js` contains its own checks for failing images, but these will be removed in #127.
~~* In the old implementation, the minimum image dimensions are 200x200 (see `yoast-social-previews/js/facebookPreview.js`), but in the `FacebookImage` component (in `javascript/packages/social-metadata-previews`), the minimum image size is set to 158x158. The specs should be clear before someone starts working on this issue.~~

## To do
- [ ] Implement the requirement checks.
- [ ] Show a warning if a requirement is not met.
- [ ] Write tests for the requirement checks.
- [ ] Update/create a snapshot for the component.

**Comment by jono-alderson** [comment]
Let's keep the min at 200x200, given that we know that some (unpleasant) scaling happens below that.

**Comment by johannadevos** [comment]
Alright! 

In comparison to the Twitter image requirements (#212), the list of requirements for Facebook is very short. Are there any other requirements that we should be aware of, like file types? (No such requirements are implemented in the older and current versions of the code)

**Comment by jono-alderson** [comment]
Check the restrictions we place on the `og:image` output; should all be equivalent.

**Comment by thijsdevalk** [comment]
So, I'm guessing we just need two notifications here, since we don't check on anything else?

- The image you are trying to upload is too small. The minimum dimensions for this image are 200x200 pixels.
- Something went wrong with the uploaded image. Please try uploading the image again.

**Comment by GuidoOffermans** [comment]
fixed in #503
