### ISSUE TITLE
The 'UI' of `yarn link-monorepo` is not intuitive and results in common errors

### ISSUE THREAD

**Issue by atimmer** [Yoast/javascript#218]
## Explanation

When you run `yarn link-monorepo` the following happens:

1. you clone into a new or already existing `/javascript` folder.
2. In this repository `yarn link-all` is run.
3. `yarn link [package]` is run for every package.

## The problem 

* These steps don't always result in the packages in `/javascript` being linked. This is because you could have already have a package available to yarn somewhere, in that case the package is linked to there.
* The other problem is that it is not immediately clear which packages you are using.

Those two things result in a lot of wasted time for developers.

## How should it work

When you run `yarn link-monorepo` the following should happen:

* If a `.yoast` is present with a `monorepo-location` property:
    * The script goes to that directory and runs `yarn link-all`.
* If a `.yoast` is not present or the monorepo-location is not present:
    * The script asks: "Where is your monorepo git clone located"
    * The answer to this value is saved to the `.yoast` file in the monorepo-location property.
    * If a clone of the `Yoast/javascript` monorepo doesn't exist in this location yet, we clone `Yoast/javascript`.
    * We run `yarn link-all` inside the given location of the monorepo.
* We do `yarn link [package]` for every package.

## Technical decisions

* The script should be written in JavaScript. Because it will become more involved over time.

**Comment by diedexx** [comment]
This script should overwrite any existing links

**Comment by diedexx** [comment]
@atimmer please share your knowledge on reading files with JS

**Comment by atimmer** [comment]
In general you can read files using node.js with readFile: https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_readfile_path_options_callback. 

Because we are in a command line script it is not a problem to do this synchronously, so you can use `readFileSync`: https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_readfilesync_path_options

**Comment by atimmer** [comment]
One additional thing: Make sure the `.yoast` file is JSON/YAML so we can add other values to it later.
