### ISSUE TITLE
Fill in constructMetaData on the PaperParser

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#219]
## Explanation
In #188 we create the PaperParser class. Currently there is no functionality to map the attributes to the metaData format we need, using morphology.

## Technical decisions
You could create these mapping functions as standalone utility functions in `parsedPaper/build/metadata`.

You should use these mapping functions in the `PaperParser.constructMetaData`.

You can get inspiration from the `collectKeyphraseAndSynonymsForms` function in `buildKeywordForms.js`.

I might be wise to implement some sort of cache, so that we do not have to recreate any forms using morphology if a specific attribute in the paper did not change.

_This spec is not complete, because I'm in a hurry and I don't have a complete overview of the functionality we need to implement._

## Feedback?
@atimmer @hansjovis 
Please expand where needed.

Requires #188

**Comment by manuelaugustin** [comment]
This issue is closed because changes in the tree parser architecture have most likely obsolete. Can be re-opened if necessary.
