### ISSUE TITLE
Remove TreeBuilder class

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#222]
## Explanation
In #187 we created a TreeBuilder class, but we noticed that the builder function does not need to be a class. Rather, we now instantiate PaperParsers by injecting a build-function into them. Please remove the TreeBuilder and its usages from the package.

Where TreeBuilder.build is called, you can use buildTree for now, I reckon.

**Comment by manuelaugustin** [comment]
This issue is closed because changes in the tree parser architecture have most likely obsolete. Can be re-opened if necessary.
