### ISSUE TITLE
Make the SvgIcon component able to take an alternate icon set

### ISSUE THREAD

**Issue by afercia** [Yoast/javascript#229]
Context: https://github.com/Yoast/my-yoast/issues/1576#issuecomment-483613494

For better re-use in other applications, the `SvgIcon` component should be able to accept an alternate/additional set of icons. 

At the moment, it uses only the icons defined in its own `icons` object. Exposing this object as an `iconSet` prop would allow to manipulate the default icon set in different ways for example:
- completely replace the default icon set with another one
- add new icons to the default ones

**Comment by afercia** [comment]
@atimmer when you have a chance :) does this sound like a worthwhile improvement?

**Comment by atimmer** [comment]
Yes this would be an improvement.
