### ISSUE TITLE
Localization errors when running tests

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#233]
## Explanation

When running `yarn test` in the root of the project, all tests are run. A lot of those tests have Jed localization errors, which makes it hard to see if there are tests that are actually failing. 

Example:
<img width="462" alt="Schermafbeelding 2019-04-17 om 10 42 47" src="https://user-images.githubusercontent.com/17744553/56273856-e8c92700-60fd-11e9-8c9f-2f87f5a47ee2.png">

Make sure all tests have a Domain that can be found, so those errors are not thrown anymore.

**Comment by atimmer** [comment]
The following issue is not required, but makes this issue easier: https://github.com/Yoast/javascript/issues/135.
