### ISSUE TITLE
Validation warning in algolia-search-box test

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#234]
## Explanation

When running `yarn test` in the root of the project, all tests are run. However, in the algolia-search-box tests, the following warning is thrown:
<img width="756" alt="Schermafbeelding 2019-04-17 om 10 43 01" src="https://user-images.githubusercontent.com/17744553/56274101-64c36f00-60fe-11e9-9b9d-89b7bd442543.png">

I'm not sure whether this actually breaks anything, but having warnings in the tests makes it harder to see if there are tests that are actually failing.

**Comment by Djennez** [comment]
Closing this, as Algolia has been removed from the plugin with the introduction of the new HelpScout beacon.
