### ISSUE TITLE
Document the 'integration points' with the plugin

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#235]
## Explanation

The past few weeks, team plugin and team lingo saw a lot of errors that were caused by missing steps in the linking/building process. Therefore, I would love to have a wiki (or another overview) which documents what steps need to be taken to have a functional combination of this monorepo and the plugin. 

This should include at least the following things:
- How to link the monorepo.
- How to unlink the monorepo.
- What monorepo-related build steps to do when having the monorepo linked.
- What monorepo-related build steps to do when using released/RC versions of the monorepo packages in the plugin's package.json (if any).

The document should include literally all steps/commands for each of those things.

**Comment by IreneStr** [comment]
Command to view all linked packages, including @yoast packages: `{ ls -l node_modules | grep ^l & ls -al node_modules/@yoast | grep ^l }`

**Comment by diedexx** [comment]
Note for team Meta: https://yoast.slack.com/archives/C0361PEK4/p1555665591067600

**Comment by LisanneKluitmans** [comment]
This also includes this issue: #245
