### ISSUE TITLE
Don't default to develop when executing yarn link-monorepo

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#240]
## Explanation

https://github.com/Yoast/wordpress-seo/pull/12724 introduced a new `yarn link-monorepo` script. This change already improved the UI, but there is still one remaining issue: it defaults to the develop branch of the Javascript repo. There are at least two scenarios in which this is annoying:
- When having uncommitted changes on a specific Javascript branch, and wanting to test these in the plugin. 
- When having tested (committed or uncommitted) changes on a specific Javascript branch in Free, and wanting to test them in Premium as well. 

In both these scenarios, it would be more intuitive if the Javascript branch that is currently checked out locally would be linked instantly. This would prevent uncommitted changes from being taken to develop, and confusion when testing a change in both Free and Premium.

**Comment by diedexx** [comment]
We will only checkout another branch in the monorepo script if running on Travis.
