### ISSUE TITLE
Add information to README about which packages there are

### ISSUE THREAD

**Issue by atimmer** [Yoast/javascript#245]
## Problem

When someone wanting to contribute to one of our packages they are not greeted with a nice index that helps them where to go.

## Explanation

[The current README.md](https://github.com/Yoast/javascript/blob/develop/README.md) is a bit barren. We should add information which packages are located in this monorepo and a summary for what each of the packages are meant for.

Don't forgot to include which apps there are and what their use is.

**Comment by LisanneKluitmans** [comment]
This issue will be picked up together with #235
