### ISSUE TITLE
Match TwitterPreview font styling with Twitters' previews.

### ISSUE THREAD

**Issue by hwinne** [Yoast/javascript#256]
## Explanation
Our TwitterPreview has different font styling than the original font styling on Twitter.
Check if the margins are still correct after changing the styling.

## Technical decisions
Twitter uses for the TwitterTitle:
`font-family: "Helvetica Neue", Helvetica, Arial, sans-serif`
`font-size: 14px`
`line-height: 18px`
`font-weight: 700`

Twitter uses for the TwitterDescription:
`font-family: "Helvetica Neue", Helvetica, Arial, sans-serif`
`font-size: 14px`
`line-height: 18px`
`font-weight: 400`
 
Twitter uses for the TwitterSiteName:
`font-family: "Helvetica Neue", Helvetica, Arial, sans-serif`
`font-size: 14px`
`line-height: 18px`
`font-weight: 400`
`color: #8899a6`
`color: rgb(136, 153, 166)`

Twitter screenshot
![image](https://user-images.githubusercontent.com/42736463/56972281-0325ea80-6b6b-11e9-8ec3-297cdd82dc6f.png)

Yoast TwitterPreview screenshot
![image](https://user-images.githubusercontent.com/42736463/56972514-6adc3580-6b6b-11e9-9739-e366099afdef.png)

## Feedback?
@IreneStr 

parent #48

**Comment by maartenleenders** [comment]
Fixed in #477 
Also, outdated:
![image](https://user-images.githubusercontent.com/26220788/73539020-b5594e00-442c-11ea-8f6c-3702dd10495b.png)
