### ISSUE TITLE
Adapt TwitterTextContainer if the description is only one line

### ISSUE THREAD

**Issue by hwinne** [Yoast/javascript#257]
## Explanation
Find out a way to determine if the description of a `large image summary card` is one or two lines. If the description is only one line, the `height` of `TwitterTextContainer` should be `84px`. In #157 the number of lines will probably be used to truncate, so these issues could perhaps be helpful to one another.

## Technical decisions
When the description consists of one line, make `height: 84px` in the styled component `TwitterTextContainerWrapper`

## Feedback?
@IreneStr 

Parent #48

**Comment by IreneStr** [comment]
This will be fixed in https://github.com/Yoast/javascript/issues/51
