### ISSUE TITLE
Remove react-test-renderer dependency from @yoast/helpers

### ISSUE THREAD

**Issue by Xyfi** [Yoast/javascript#271]
## Explanation

Currently, we are trying to reduce the bundle size of the premium plugin. We are running into the following problem:

There is a function in `@yoast/helpers` (`createComponentWithIntl`) that requires `react-test-renderer`. This causes the plugin build to include this dependency in builds, causing the bundles to be unnecessarily big.

Since we don't use `react-intl` anymore, we could simply remove this function?

**Comment by IreneStr** [comment]
Fixed in https://github.com/Yoast/javascript/pull/272
