### ISSUE TITLE
Combine all separate TwitterPreview components to have a working preview

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#28]
When resolving this issue we should have the following components:
* [ ] TwitterTextContainer https://github.com/Yoast/javascript/issues/51
* [ ] TwitterImage https://github.com/Yoast/javascript/issues/50

These components should be combined in the `TwitterPreview` component something like:
```
    return ( <div>
          <TwitterImage src={ props.image } />
          <TwitterTextContainer
            ...
           />
       </div>
    );
```

Reference:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

Parent of https://github.com/Yoast/javascript/issues/51
Parent of https://github.com/Yoast/javascript/issues/50
Parent of https://github.com/Yoast/javascript/issues/209

**Comment by omarreiss** [comment]
Fixed elsewhere.
