### ISSUE TITLE
Snapshots in the plugin are unstable

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#285]
## Explanation

The builds on wordpress-seo and wordpress-seo-premium are constantly failing because of non-matching snapshots. One day we update the snapshots in the release branch to let that Travis build pass, the next day we release, and the Travis build on `master` is broken because of snapshots that are expected to look like the state before yesterday's snapshot update. 

Example 1:
- Failing Travis on release/11.3, because it expects different classnames in the snapshots: https://travis-ci.org/Yoast/wordpress-seo/jobs/532827137
- The commit that fixes it by locally running `yarn link-monorepo` and updating the snapshots (`yarn test -u`) afterwards: https://github.com/Yoast/wordpress-seo/commit/156b1369011d692c3c8b24d3dd294dc3f4ce8ef9
- Succeeding Travis after updating the snapshots with the above commit: https://travis-ci.org/Yoast/wordpress-seo/jobs/532855194
- Failing Travis on master, because it expects different classnames than in the above trunk: https://travis-ci.org/Yoast/wordpress-seo/jobs/533266388. Reverting the above mentioning commit would make Travis pass.

Example 2:
- Succeeding Travis on for the `11.3-RC2` tag: https://travis-ci.com/Yoast/wordpress-seo-premium/builds/112190760
- Failing Travis on exactly the same commit on `release/11.3`: https://travis-ci.com/Yoast/wordpress-seo-premium/jobs/200970193

We really need to fix this, because this takes way to much time and frustration, and leads to inconsistent and therefore unreliable snapshots. In the past few weeks, more than once an RC was delayed because of failing snapshots related to this problem.

## Technical decisions

Not really a decision, but the hypothesis is that it has something to do with which version of the monorepo is used in each of the builds (master, trunk, release/x.x, hotfix/x.x.x). In some cases it's linked, in other cases it's using released versions of the monorepo.

## Feedback?

Feedback about the hypothesis, and alternative hypotheses, from the meta team would be appreciated (@andizer @diedexx @bintzandt).

**Comment by bintzandt** [comment]
Closing this issue for now. If it turns out that the snapshots are still unstable please open this issue again and provide a detailed explanation of what goes wrong.
