### ISSUE TITLE
Refactor configuration wizard to use __ instead of intl provider

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#33]
## Summary
We want to use `__` over `intl`. Therefore we are removing the `intl` from the ConfigurationWizard and making sure that `__` is used instead of it.

**Comment by diedexx** [comment]
for context: `intl` is the old way of translating we used, `__` is the new WordPress way to manage translating your interface.

1. Replace intl with __ (of _n, or _x etc.) in code.
1. Check if the translation pipeline still works
  1. `grunt build:i18n` in the plugin parses the code.
    1. See if all __ strings are present in the generated files.
1. Check if the existing translations are properly translated with the __ function
