### ISSUE TITLE
Fix alignment in the internal linking suggestions sidebar

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#333]
PR: https://github.com/Yoast/javascript/pull/360
## Explanation

The list of suggested posts does not seem to always be properly aligned. From what I can see, the problem happens on an article following an article with a short title (that takes 1 line). Remarkably enough, if a heading `Consider linking to these articles` follows a (cornerstone) article with a short title, the alignment problem occurs there as well.
<img width="230" alt="Screenshot 2019-08-05 at 15 38 37" src="https://user-images.githubusercontent.com/36954173/62518506-01cf2280-b82a-11e9-8cb6-a062308a123c.png">
In my case, the alignment issue occurred in Google Chrome, but @dariaknl also replicated it with Safari. Namely, [this post](https://staging.yoast.com/wp/wp-admin/post.php?action=edit&post=1695906) received the following linking suggestions:
<img width="1188" alt="Screenshot 2019-08-08 at 15 42 58" src="https://user-images.githubusercontent.com/36954173/63747341-36714f80-c8a7-11e9-9176-880a8ab92a62.png">

**Comment by manuelaugustin** [comment]
Possible solution: give a minimal height to the div that contains the text
