### ISSUE TITLE
Improve user messages in the Internal Linking suggestions sidebar

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#334]
## Explanation

In the Gutenberg sidebar, under the Internal linking suggestions collapsible, we render a number of user messages with recommendations on how to improve their internal linking.

I believe that we can improve the copy of the user messages to make them less lengthy and more to the point. Right now, we, for instance, return this much text if no suggestions were found:

<img width="235" alt="Screenshot 2019-08-02 at 15 28 35" src="https://user-images.githubusercontent.com/36954173/62520487-fed63100-b82d-11e9-8ec8-4fa87364bc91.png">

The entire overview of how user messages are being determined is available in [this google sheet](https://docs.google.com/spreadsheets/d/1nc6uuqlWsJMdct6uJ8VbMs4kAFWJu_8kPLAk5Cu3TvE/edit?usp=sharing).

## Feedback?
@thijsdevalk Do you find this issue deserves to be fixed? If so, do you have any further feedback for us on how we could improve the messages?

**Comment by thijsdevalk** [comment]
This is not an issue to me. The copy is clear and should be a bit more descriptive because this won't be the best or most understood thing to most people using Yoast SEO.

**Comment by nataliashitova** [comment]
Check. Closed.
