### ISSUE TITLE
Reconsider link text in Internal Linking suggestions sidebar

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#335]
## Explanation

In the Gutenberg sidebar, under the Internal linking suggestions collapsible, we render a number of user messages with recommendations on how to improve their internal linking.

The link in one of the user messages points to [this article](https://yoast.com/why-use-yoast-internal-linking) that mostly focuses on how to use the Internal Linking Suggestions tool, while the text rather suggests a guide on site structure.

<img width="230" alt="ArticleLink" src="https://user-images.githubusercontent.com/36954173/62518727-773af300-b82a-11e9-895e-2be60d3ca7eb.png">

I think the use of this article is very purposeful, so we could consider changing the link text to match the content of the article better.

This issue is related to #334, which addresses all user messages in the Internal linking suggestions sidebar.

## Feedback?
@thijsdevalk Do you find this issue deserves to be fixed? If so, how would you change the message copy?

**Comment by thijsdevalk** [comment]
I agree. I think it should simply be linked to https://yoast.com/site-structure-the-ultimate-guide/

**Comment by manuelaugustin** [comment]
Note: for this link we also need a short link + UTM tags.

**Comment by atimmer** [comment]
Because only the link had to be changed and the shortlink that was in use there wasn't used anywhere else, the link has been changed in the shortlink system.
