### ISSUE TITLE
Add Dutch noun suffixes

### ISSUE THREAD

**Issue by agnieszkaszuba** [Yoast/javascript#355]
PRs:
https://github.com/Yoast/javascript/pull/356
https://github.com/Yoast/YoastSEO.js-premium-configuration/pull/58

We should attach noun suffixes (plural and diminutive) to stems of Dutch words in order to create noun forms. E.g., we want to create the forms _katten_ and _katje_ when the stem is _kat_. This may also involve modifying the stem before adding suffixes (e.g. the _t_ in _kat_ should be doubled before adding the suffix -_en_)

**Comment by nataliashitova** [comment]
The PRs were merged. Therefore, closing this issue.
