### ISSUE TITLE
Add Dutch stemming exceptions

### ISSUE THREAD

**Issue by agnieszkaszuba** [Yoast/javascript#364]
PR: https://github.com/Yoast/javascript/pull/366
PR (premium config): https://github.com/Yoast/YoastSEO.js-premium-configuration/pull/62
 
We should add exception checks to the stemmer in order to stem words that do not follow the pattern defined by the existing rules.

**Comment by nataliashitova** [comment]
Premium Configuration PR: https://github.com/Yoast/YoastSEO.js-premium-configuration/pull/62

**Comment by manuelaugustin** [comment]
Closed via https://github.com/Yoast/javascript/pull/366
