### ISSUE TITLE
Move CornerstoneContent to the plugin

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#37]
## Summary
CornerstoneConent is currently located in yoast-components/composites/Plugin/CornerstoneContent. However, since this is simply a toggle with some text above it **and** because it is used in only a few locations (maybe even 1) we want to remove it from yoast-components. Instead, the CornerstoneContent should directly be used at the places where it is currently used.

**Comment by atimmer** [comment]
@bintzandt Just found out the Cornerstone toggle is still used here: https://github.com/Yoast/javascript/blob/develop/apps/components/UIControlsWrapper.js#L5. Make sure to remove that when you remove it in `Yoast/javascript`.

**Comment by diedexx** [comment]
> Just found out the Cornerstone toggle is still used here: /apps/components/UIControlsWrapper.js@develop#L5. Make sure to remove that when you remove it in Yoast/javascript.

That's been done in https://github.com/Yoast/javascript/pull/185
