### ISSUE TITLE
Merge MyYoastManage into the JS monorepo

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#4]
## Summary

The MyYoastManage package has to be merged into the javascript monorepo.

## Explanation

yoast-social-previews, yoastSEO.js, yoast-components, my-yoast client, my-yoast manage and eslint are all merged into the same monorepo to keep all javascript together.

## Technical decisions

All mentioned existing repos above will be placed in their own packages in the monorepo.

**Comment by diedexx** [comment]
See https://github.com/Yoast/javascript/issues/3#issuecomment-472349339 on how this needs to be done.

**Comment by omarreiss** [comment]
Lets not do this for now.
