### ISSUE TITLE
Create a base `Assessment` class

### ISSUE THREAD

**Issue by atimmer** [Yoast/javascript#413]
## Explanation

This is the base for every new tree assessment.

## Technical decisions

Use the old `Assessment` class as inspiration.

The `TreeAssessment` object should have the following methods that MUST be implemented in a child classes:

* async `getResult` Same arguments and return value as `Assessment.getResult` except that the return value should be returned in a Promise.
* async `isApplicable` Same arguments and return value as `Assessment.isApplicable` except that the return value should be returned in a Promise.

TBD
* async `markTree`:

**Comment by manuelaugustin** [comment]
Fixed in https://github.com/Yoast/YoastSEO.js/pull/2142
