### ISSUE TITLE
Gutenberg code block throws a console error in the TreeAdapter

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#427]
## Explanation

If a text contains a Gutenberg code block the current version of the TreeAdapter fails.

<img width="1263" alt="Screenshot 2019-12-20 at 11 04 55" src="https://user-images.githubusercontent.com/36954173/71247221-95f0e080-2318-11ea-8bf6-66dea1280d5f.png">

### Impact
The error does not affect text analysis, because the treeparser is not being used for actual analysis yet.
We might still want to switch the tree parser off for Gutenberg for now, until a decision is made which Gutenberg blocks we support and how we should treat blocks we do not support. @JessieHenkes

**Comment by nataliashitova** [comment]
See also for a custom block issue https://github.com/Yoast/wordpress-seo/issues/14067 (that does affect the analysis).

**Comment by hansjovis** [comment]
I have an idea.
We can use the logLevel logger to only log the error when the `YOAST_SEO_DEBUG_ANALYSIS_WORKER` debug flag has been enabled. This way we can still see the error when debugging, but the user should not see them anymore.

This would be as easy as replacing the appropriate `console.error` statement with `logger.debug`.

**Comment by nataliashitova** [comment]
Whether the code block still generates an error in the TreeAdapter will be checked in acceptance testing of this issue https://github.com/Yoast/javascript/issues/423.

**Comment by igorschoester** [comment]
It does not generate an error anymore -- closing
