### ISSUE TITLE
Create a TwitterSiteName component

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#43]
The `TwitterSiteName` will be shown as a span:
<img width="526" alt="yoast___yoast____twitter" src="https://user-images.githubusercontent.com/325040/49155773-14e53680-f31c-11e8-9376-dbc8c53c13f6.png">

The sitename only contain the 'domain' part. The scheme and the path should be stripped out. Also strip the `www.` part if that is left. But keeping the subdomains. For example: `2019.us.wordcamp.org` is a valid sitename.

## Styling
The styling for this will be:
```css
    text-transform: lowercase;
    color: #8899A6;
    max-height: 18.2px;
    line-height: 18.2px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    margin-top: 4.52662px;
```

Parent #51

**Comment by afercia** [comment]
I'm curious to understand what is the reasoning behind providing decimal values for unit expressed in _pixels_. For example: `4.52662px`. As mentioned also in the case for the Facebook Preview, pixels on the screen can't be split in decimal parts. These values get rounded anyways. To not be confused with the computed value you see in the dev tools: those are the result of a computation and often display decimals. However, on the screen, the actual size is a full pixel.
