### ISSUE TITLE
Create Redux store for the facebook previews

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#440]
Parent #444
Needs #442 

This issue is split in several sub-issues. This issue serves as an overview of those issues and has two (simple) tasks itself.

We have to create a Redux store for storing the data entered in the Facebook previews. The store should contain values for:
* Title
* Description
* Image
* Type
* Author (static value)
* SiteName (static value)

### Reducer
The reducers for the Facebook preview should have the following state:
```
INITIAL_STATE = {
  title: "",
  description: "",
  imageUrl: "",
  imageId: "",
  author: "",
  siteName: "",
  errors: [],
  type: "",
}
```

Make sure the reducer handles everything.

### Actions
- [x] Create an action that will set the value for `FacebookTitle`
- [x] Create an action that will set the value for `FacebookDescription` 
- [x] Create an action that will set the value for `FacebookImage` 
- [x] Create an action that will set the value for `FacebookImageType`. This depends on the dimensions of the used image. 

Note: The author depends on the set Facebook profile url set in the authors' user profile. It can't be changed. The sitename is the name of the site and can't be changed by the user.

### Selectors
- [ ] Create a selector that retrieves the value for the `FacebookTitle`. 
   - If the value isn't set we should return one of the 'fallback' values (snippet preview, post title, site wide default). 
- [ ] Create a selector that retrieves the value for the `FacebookDescription`. 
   - If the value isn't set we should return one of the 'fallback' values (meta description, post excerpt/taxonomy description, side wide default). 
- [ ] Create a selector that retrieves the value for the `FacebookImage`. 
   - If the value isn't set we should return one of the 'fallback' values (featured image, content image, side wide default).
- [ ] Create a selector that retrieves the value for the `FacebookImageType`. The values depends on the dimension of `FacebookImage`. 
- [ ] Create a selector that retrieves the value for the `FacebookAuthor`. This should return the value that is set by localization. This is a static value that can't be changed.
- [ ] Create a selector that retrieves the value for the `FacebookSiteName`. This should return the value that is set by localization. This is a static value that can't be changed.

### Other
- [ ] Create a reusable set of reducer, actions and selectors. See https://redux.js.org/recipes/structuring-reducers/reusing-reducer-logic/.
- [ ] Make sure action types can be prefixed with a unique prefix.
- [ ] Write a README.md how to use the reusable reducer.
- [ ] Write tests.

**Comment by maartenleenders** [comment]
Splitting out the Selector's responsibility for selecting fallback values to https://github.com/Yoast/javascript/issues/492

This way we can keep this issue moving, and easily add fallback selectors once we know where the fallbacks will be placed in the store.

**Comment by GuidoOffermans** [comment]
implemented in https://github.com/Yoast/javascript/pull/494
