### ISSUE TITLE
Create form for managing the Facebook (preview) data

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#443]
For managing the Facebook data and reflecting this data in the preview we need a form where we can enter:
- The title
- The description
- The image

This form should manage the values in the #440 

### How it looks like
<img width="577" alt="Screen Shot 2020-02-04 at 10 01 30" src="https://user-images.githubusercontent.com/6073772/73729447-5863dd80-4735-11ea-9f1c-eec99924228d.png">

### The elements
- [x] Create an input element for the title. 
   - [x] The label has `Facebook title` as value
   - [x] This element should be support inserting variables (these are the replace_vars in the code). 
   - [x] When the value has changed it should trigger the action for updating the title in the store.
- [x] Create an textarea for the description. 
   - [x] The label has `Facebook description` as value
   - [x] Just like the title element this element should have support for inserting variables as well. 
   - [x] When the value of the textarea is changed it should trigger the action for updating the description in the store.
- [x] Create a button for setting the image. This element can use the media library in WordPress for selecting an image. 
   - [x] The label has `Facebook image` as value
   - [x] When an image is selected it should trigger the action for updating the image in the store. 

Parent https://github.com/Yoast/javascript/issues/444

**Comment by Xyfi** [comment]
* Create an abstract `SocialMetadataPreviewForm` component.
  * Pass the values for the fields as props
  * Pass the on change callbacks for the fields as props
  * Pass the replacement variables as props (look at the Snippet preview editor)
* Create a wrapper for Facebook.

**Comment by bintzandt** [comment]
I have attached a PR to this issue. This PR is far from complete but it should provide a solid starting point for the person that is going to pick up this issue. I have documented what still needs to be done on the PR (in the section `TODO`).

**Comment by maartenleenders** [comment]
Implemented in https://github.com/Yoast/javascript/pull/484
