### ISSUE TITLE
Update draft-js to the latest version

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#445]
We are using 0.10.4 which was released 2 years ago. Since that release [0.11.0](https://github.com/facebook/draft-js/releases/tag/v0.11.1) has been released and that version contains **A LOT** of changes. We should update draft-js to the latest version.

### To do:
- [ ] Update draft-js to the latest version 0.11.4
- [ ] Test if everything still works

**Comment by bintzandt** [comment]
@maartenleenders: Closed by #478
