### ISSUE TITLE
Create a FacebookPreview component

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#45]
The Facebook preview wrapper component (`FacebookPreview`) contains the whole Facebook preview.

<img width="518" alt="yoast_-_home" src="https://user-images.githubusercontent.com/325040/51474357-51af3600-1d7f-11e9-88e4-4e0c03ae277b.png">

## Properties
This component will receive:
* title
* description
* image
* imageType (landscape, portrait or square) 
* siteName
* authorName (when applicable)

Example:
```jsx
<FacebookPreview 
    title='The title' 
    description='The description to show' 
    image='https://example.org/image.jpg' 
    imageType='square'
    siteName='domain.com'
    authorName='Jane Doe' />
```

### Styling
It should have the following CSS props:
```css
    background-color: #f2f3f5;
    max-width: none;
    border: none;
    box-shadow: none;
    border: 1px solid #dddfe2;
    border-radius: 0;
    zoom: 1;
    float: left;
    overflow: hidden;
    position: relative;
    z-index: 0;
}
```

Parent https://github.com/Yoast/javascript/issues/47

Don't forget to write tests.

**Comment by GuidoOffermans** [comment]
I didn't pass imageType  "`imageType='square'`" as a prop. In FacebookImage.js the function: determineImageProperties already calculates if it a landscape, portrait or square.
Is my assumption of this correct?
