### ISSUE TITLE
Create form for managing Twitter (preview) data

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#469]
For managing the Twitter data and reflecting this data in the preview we need a form where we can enter:
- The title
- The description
- The image

This form should manage the values in the #468.

### How it looks like
The same form as the Facebook preview can be used, except that all the names have to be changed to Twitter ;) We are also more restrictive in the images that can be used for the Twitter preview.

<img width="586" alt="form" src="https://user-images.githubusercontent.com/6073772/73729373-336f6a80-4735-11ea-9cec-63b76a48feee.png">

### The elements
- [ ] Create an input element for the title. 
   - [ ] The label has `Twitter title` as value
   - [ ] This element should be support inserting variables (these are the replace_vars in the code). 
   - [ ] When the value has changed it should trigger the action for updating the title in the store.
- [ ] Create an textarea for the description. 
   - [ ] The label has `Twitter description` as value
   - [ ] Just like the title element this element should have support for inserting variables as well. 
   - [ ] When the value of the textarea is changed it should trigger the action for updating the description in the store.
- [ ] Create a button for setting the image. This element can use the media library in WordPress for selecting an image. 
   - [ ] The label has `Twitter image` as value
   - [ ] When an image is selected it should trigger the action for updating the image in the store. 
- [ ] Write tests

Parent https://github.com/Yoast/javascript/issues/28
Needs https://github.com/Yoast/javascript/issues/443

**Comment by maartenleenders** [comment]
The forms implemented in https://github.com/Yoast/javascript/pull/484 can already generate the components above.
