### ISSUE TITLE
Add image selected state to ImageSelect component

### ISSUE THREAD

**Issue by Xyfi** [Yoast/javascript#499]
## Explanation

Add the `Remove image` button to the image selector component:

![](https://user-images.githubusercontent.com/6073772/73729505-73365200-4735-11ea-9b2f-72e4e3d36c80.png)

Designs:

https://sketch.cloud/s/2Zz4p/a/ZoZjAp

Also pass an `imageSelected` prop to the component.
  * If this is true:
    * `Select image` should change to `Replace image`
    * The `Remove image` button should be shown.

**Comment by GuidoOffermans** [comment]
👍
