### ISSUE TITLE
Merge yoast/eslint into the JS monorepo

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#5]
## Summary

The yoast/eslint repo has to be merged into the javascript monorepo.

## Explanation

yoast-social-previews, yoastSEO.js, yoast-components, my-yoast client, my-yoast manage and eslint are all merged into the same monorepo to keep all javascript together.

## Technical decisions

All mentioned existing repos above will be placed in their own packages in the monorepo.

**Comment by diedexx** [comment]
Done in https://github.com/Yoast/javascript/commit/87729cd82f99969857dce69b6fc3deaf0d68b8f9
