### ISSUE TITLE
Create a TwitterImage component

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#50]
The TwitterImage component will be rendered as an `img`
<img width="535" alt="yoast___yoast____twitter" src="https://user-images.githubusercontent.com/325040/49157633-8aeb9c80-f320-11e8-90e2-019048363ed7.png">
Example of the summary with large image card.

<img width="525" alt="_3__twitter" src="https://user-images.githubusercontent.com/325040/49157524-46f89780-f320-11e8-9d8d-4b2d85fd5a6f.png">
Example of the summary card.

## Properties
* src (full path to the image)
* type ( summary, summary-large-image) 

The type is relevant for the way we display the image. See the specifications below.

When no SRC has been given, we should show a placeholder:
<img width="462" alt="Screen Shot 2019-03-12 at 11 19 49" src="https://user-images.githubusercontent.com/6073772/54192702-db929a00-44b8-11e9-9842-c61793a417a9.png">

## Specifications
General specs for the image
* Images must be less than 5MB in size. 
* JPG, PNG, WEBP and GIF formats are supported. 
* Only the first frame of an animated GIF will be used. 
* SVG is not supported.

About the summary with large image, Twitter says:
> Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. 

And for the summary Twitter gives:
> Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels. [...] The image will be cropped to a square on all platforms.

## Styling
```css
    background-color: #E1E8ED;
```

The square will have a width and height of `123.422px`. The large image will have a width of 506px and a height of 253px.

Parent https://github.com/Yoast/javascript/issues/48

**Comment by IreneStr** [comment]
@hedgefield Twitter does use the placeholder: <img width="525" alt="Schermafbeelding 2019-03-13 om 10 31 43" src="https://user-images.githubusercontent.com/17744553/54268319-37bdf280-457b-11e9-8309-34e38bf1b30a.png">

**Comment by hedgefield** [comment]
Also for the large card?

Well, regardless, I think the placeholder icon is not as important as making it clear that the user should supply an image there, so I recommend following the drop zone design in https://github.com/Yoast/roadmap/issues/21

As for the error, I agree both Facebook and Twitter should display one when there is a problem with the image.

<img width="584" alt="Screen Shot 2019-03-13 at 13 08 04" src="https://user-images.githubusercontent.com/6073772/54279211-ca1ec000-4594-11e9-8e38-023225e3365c.png">

As for an error about unsupported filetypes, is it even possible to upload an unsupported filetype to the media library?

**Comment by IreneStr** [comment]
Please note that the above error message is not part of this issue. We'll deal with that in a later stage.

**Comment by hwinne** [comment]
What's the use of `background-color: #E1E8ED` when this background is only displayed behind the image, and therefore never visible?

**Comment by hwinne** [comment]
@johannadevos and I have pushed our work so far. What still needs to be done is:

* Checking whether an image meets the conditions (e.g., is not larger than 5MB)
* When no `src` is provided for an image, show the `Select image` field

**Comment by johannadevos** [comment]
As just discussed with @IreneStr, all the checks and the display of their corresponding error messages should be implemented in another issue (she already briefly mentioned this above). 

This means that the following part of the issue description is no longer part of the current issue:

## Specifications
General specs for the image
* Images must be less than 5MB in size. 
* JPG, PNG, WEBP and GIF formats are supported. 
* Only the first frame of an animated GIF will be used. 
* SVG is not supported.

About the summary with large image, Twitter says:
> Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. 

And for the summary Twitter gives:
> Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels.

**Comment by johannadevos** [comment]
@andizer You say that "The large image will have an width of 506px and an height of 254px". However, this is not exactly a 2:1 ratio, which should either be 508/254 or 506/253. Where did you get these sizes from, and which size should we use in the end?

**Comment by johannadevos** [comment]
> In the design for this I'm experimenting with making the image placeholder area a drop zone, since that is kind of how the facebook one works as well. Does that work for Twitter? I know facebook doesn't show any image if it can't find a suitable one. Does Twitter still show that placeholder after you post a link with no image, or is that just to there to indicate how the template works?
> 
> <img alt="Screen Shot 2019-03-12 at 11 19 49" width="462" src="https://user-images.githubusercontent.com/6073772/54192702-db929a00-44b8-11e9-9842-c61793a417a9.png">

To create this placeholder, for blue and grey I'm using values provided by @hedgefield (`#f1f1f1` and `#073CBA`). They aren't in the standard color palette, but provide more contrast for accessibility.

**Comment by afercia** [comment]
Closed in https://github.com/Yoast/javascript/pull/131
