### ISSUE TITLE
Tweak distance for caret position in Social "square" and "small" previews

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#611]
## Explanation
![image](https://user-images.githubusercontent.com/26220788/78797410-eff4df00-79b7-11ea-821b-0e56555d97fc.png)

With the reactification of the Social Previews (#607 ), we put the carets in the 
`TwitterPreview` and `FacebookPreview` at a distance that does not work when:

- The FacebookPreview is in "square" or "portrait" mode.
- The TwitterPreview is in "summary_card" mode, rather than "summary_card_large", reflected by the `isLarge` prop.

Based on those props, the caret spacing should be larger or smaller.

The styles are added in `TwitterPreview` and `FacebookPreview` like so:

```js
const TwitterTitle = withCaretStyle( NoCaretTitle, true );
const TwitterDescription = withCaretStyle( NoCaretDescription, true );
```

The `const Caret = styled.div` (line 24 `SocialMetadataPreviewForm.js`) needs to be expanded to deal with the relevant props, currently in only creates some more space depending on the inPreview prop:
```js
${ getDirectionalStyle( "left", "right" ) }: ${ ( props ) => props.inPreview ? "-35px" : "-25px" };
```

That needs to be refactored.

You can always ask me for more info if needed.

**Comment by IreneStr** [comment]
We've decided to remove the carets from the social previews
