### ISSUE TITLE
Change class name for the Explanation component

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#67]
The `Explanation` component is moved from the OnBoardingWizard directory to the `@yoast/components`. This is because a not onboarding wizard components is using it. The only thing is that the component has a class name `yoast-wizard-input__explanation` and that should be changed.

I think we should pass the class name as a property to the component.

**Comment by diedexx** [comment]
[The `Explanation` component](https://github.com/Yoast/javascript/blob/develop/packages/components/Explanation.js) is not the most meaningful component, as it's just a paragraph. Can we remove/deprecate it instead?

**Comment by diedexx** [comment]
We decided to delete the component during the sprint planning.
TODO:
- remove component
- Update usages
- Update snapshots
