### ISSUE TITLE
Focus keyphrase not recognized if the keyphrase contains a period

### ISSUE THREAD

**Issue by bettoniauto** [Yoast/javascript#77]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### How can we reproduce this behavior?
1. Possible debug it

### Technical info

* If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin
- [x] AVADA

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

#### Used versions
* WordPress version:  5.1.1
* Yoast SEO version: 10.0
* Avada  plugin version: 5.8.2

Bug Attachment:
![yoast_bug](https://user-images.githubusercontent.com/48519863/54282137-a14df900-459b-11e9-8db5-9d184547ead3.jpg)

**Comment by Djennez** [comment]
So this issue has been around longer. Closing this in favor of https://github.com/Yoast/YoastSEO.js/issues/1123 as that one is older and contains support notification triggers. @IreneStr or @moorscode would you mind moving that issue to this repository and apply the correct labels?
