### ISSUE TITLE
Move wp-dashboard-widget files

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#80]
## Summary

We want to have structured packages for all our components. To achieve this, we need to move the wp-dashboard-widget files to other packages.

## Explanation

- This AssesmentResult file needs to be renamed to SiteSEOReport and moved to the new @yoast/analysis-report package:
javascript/packages/yoast-components/composites/Plugin/DashboardWidget/components/SeoAssessment.js

- This WordPressFeed file needs to be renamed to ArticleList and moved to the new @yoast/components package:
javascript/packages/yoast-components/composites/Plugin/DashboardWidget/components/WordpressFeed.js

- This StackedProgressBar file needs to be moved to the new @yoast/components package:
javascript/packages/yoast-components/composites/Plugin/Shared/components/StackedProgressBar.js

## Technical decisions

The version of the new packages needs to be 0.1.0

**Comment by diedexx** [comment]
Blocked until https://github.com/Yoast/javascript/issues/76 is merged

**Comment by bintzandt** [comment]
This issue is not really blocked IMO. It is just a question of who is going to fix the merge-conflicts. For now I'm unblocking this so that it can move through the process.
