### ISSUE TITLE
Screenreader doesn't handle facebook sitename and author well

### ISSUE THREAD

**Issue by IreneStr** [Yoast/javascript#89]
The following Facebook sitename and author are pronounced like 'Sitename dot C O M vertical line B Y John D O E' by VoiceOver:
<img width="239" alt="Schermafbeelding 2019-03-20 om 10 19 00" src="https://user-images.githubusercontent.com/17744553/54677868-1e312380-4b04-11e9-99d5-8079b3189337.png">

Adding `aria-hidden="true"` to the span that contains the `|` does solve the 'vertical line' problem, but since we also have to deal with the capital letters problem, adding an `aria-label` might be a better option.

Parent: https://github.com/Yoast/javascript/issues/47

**Comment by afercia** [comment]
Worth noting this happens also on Facebook:

<img width="638" alt="Screenshot 2019-03-20 at 13 44 03" src="https://user-images.githubusercontent.com/1682452/54685320-d49e0400-4b16-11e9-8a4e-08a8ab8f9901.png">

most of the text in the example above gets pronounced as single letters:
`yoast dot c o m by r e m k u s  de  v r i e s`

It would be great if FB could improve the way uppercase text is announced by screen readers. We can do a bit better than FB and provide a lowercase string only to screen readers.
