### ISSUE TITLE
Review ESLint configuration for yoast-components

### ISSUE THREAD

**Issue by afercia** [Yoast/javascript#99]
Turns out we've updated the ESLint configuration for [wpseo free](https://github.com/Yoast/wordpress-seo/pull/11099), [premium](https://github.com/Yoast/wordpress-seo-premium/pull/2036), and [MyYoast](https://github.com/Yoast/my-yoast/pull/2005), but we haven't for yoast-components.

The yoast-components still run the old set of rules from Yoast/eslint 4.0.0.

A few questions:
- I see this change for packages/yoastseo https://github.com/Yoast/javascript/commit/de31da0dfc4e9c1623ad6fc25eb235719f8dbc35 which refers to a Yoast/eslint version 5.0.6. This version doesn't actually exist in the [eslint repo](https://github.com/Yoast/eslint/), I'm guessing it's a special setup to get the rules from `packages/eslint/` instead?
- shouldn't we do the same for yoast-components? What is the purpose of `packages/eslint/` if then we're still using `eslint-config-yoast` in the various `package.json`? 
- worth noting at the moment the new `packages/components` doesn't have any ESLint task

/Cc @atimmer

**Comment by atimmer** [comment]
> I see this change for packages/yoastseo de31da0 which refers to a Yoast/eslint version 5.0.6. This version doesn't actually exist in the eslint repo, I'm guessing it's a special setup to get the rules from packages/eslint/ instead?

We've moved the ESLint configuration to this repository.

> shouldn't we do the same for yoast-components? What is the purpose of packages/eslint/ if then we're still using eslint-config-yoast in the various package.json?

Yes. Added to that: If the version of `eslint-config-yoast` is correctly set in yoast-components it will automatically be kept up to date with the version in `packages/eslint/`.

> worth noting at the moment the new packages/components doesn't have any ESLint task

That's an oversight, all packages in this repository should have a lint task.

**Comment by atimmer** [comment]
I've fixed this, the only remaining issue is https://github.com/Yoast/javascript/issues/136
